
spring:
  application:
    name: ai-code-generation

server:
  port: 8125
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yzj.aicodegeneration.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

