
spring:
  application:
    name: ai-code-generation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_generation
    username: root
    password: hsp
  data:
    redis:
      host: localhost
      port: 6379
#      password: 123456
      ttl: 3600 #过期时间1小时
  profiles:
    active: local #激活本地环境

server:
  port: 8125
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yzj.aicodegeneration.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

